### ISSUE TITLE
about scale_factor

### ISSUE THREAD

**Issue by ruanjiyang** [williamyang1991/StyleGANEX#1]
Dear Williamyang1991:

thanks for your nice work.

I want to generate the video with younger face, is the following command correct?

python video_editing.py --ckpt pretrained_models\styleganex_edit_age.pt  --data_path data\2.mp4 --scale_factor 2

what's the real meaning of scale_factor?

thanks.

**Comment by williamyang1991** [comment]
--scale_factor -2

editedw = w + scale_factor * v
where w is the latent code, v is the editing vector, scale_factor is a weight
if scale_factor  = 0, no editing.
if scale_factor > 0, there is a postive editing; <0, a negative editing.

**Comment by ruanjiyang** [comment]
Thanks for your rapid feedback.

what's the reasonable scale_factor scrope for age editting? -10 ~10 ?

**Comment by williamyang1991** [comment]
normally, -2 ~ 2
