### ISSUE TITLE
Face attribute editing

### ISSUE THREAD

**Issue by dongyun-kim-arch** [williamyang1991/StyleGANEX#12]
Awesome work. Vtoonify was amazing, but StyleGANEX is even better.

<img width="1049" alt="Screenshot 2023-08-10 at 1 52 51 PM" src="https://github.com/williamyang1991/StyleGANEX/assets/70664694/6aec496e-a41b-4a0b-a6dd-bda768f5d072">

Especially, I am interested in face attribute editing (video), but I can only test age and hair editing. As shown in the example (open mouse, smile, gender swap, etc), how can I edit the face attributes?

Is training StyleGANEX necessary?
It would be great if you could elaborate how to get different face attribute editing step by step.

Thank you! :)

**Comment by williamyang1991** [comment]
Yes.
For image editing, no training is required.
For video editing, to achieve fast inference and temporal consistency, you need to train on your target face attribute following https://github.com/williamyang1991/StyleGANEX#video-editing-1
