### ISSUE TITLE
inversion

### ISSUE THREAD

**Issue by 123456klk1** [williamyang1991/StyleGANEX#14]
Hi, I'm interested in your work, Here are my inversion results, the inversion is a bit fuzzy (blocky pixels), Is this normal?
![00000](https://github.com/williamyang1991/StyleGANEX/assets/53042912/78c6e705-30ff-4e98-a5a4-d3f0d0ea94de)
![00000_inversion](https://github.com/williamyang1991/StyleGANEX/assets/53042912/763a90f5-4231-4e9b-9e8a-b4088232a0e7)

![00001](https://github.com/williamyang1991/StyleGANEX/assets/53042912/f675baa6-2dc6-4772-b7e3-88b91b7e7e76)
![00001_inversion](https://github.com/williamyang1991/StyleGANEX/assets/53042912/b93dcc10-c7cc-4079-bdb6-a7713c8164f1)

**Comment by williamyang1991** [comment]
You can try apply some gaussain blurring to the input image. 
For very high-resolution images,  bilinear downsampling will lead to too sharp low-resolution image, which will cause your artifacts.

https://github.com/williamyang1991/VToonify/blob/35922e049acad7c87c058929b15cef44c9968b30/style_transfer.py#L124-L129

**Comment by 123456klk1** [comment]
![00001_inversion](https://github.com/williamyang1991/StyleGANEX/assets/53042912/b5004993-d36d-49cb-8188-e62c089a7060)

Code as above:
kernel_size = (3, 3)
sigma = 1.5    
 y_hat[0] = transforms.GaussianBlur(kernel_size, sigma)(y_hat[0])

Looks like the picture is still a little blurry.

**Comment by williamyang1991** [comment]
As in https://github.com/williamyang1991/VToonify/blob/35922e049acad7c87c058929b15cef44c9968b30/style_transfer.py#L124-L129
My blur kernel is 4*4, and will apply it to the image twice for very large input.

**Comment by sibadakesi** [comment]
You can try pillow to resize pic, this works for me。

**Comment by 123456klk1** [comment]
Ok, thanks
