### ISSUE TITLE
关于输入输出分辨率不一致问题，如何才能保证输入输出分辨率一致？

### ISSUE THREAD

**Issue by zhanghongyong123456** [williamyang1991/StyleGANEX#15]
我输出之后resize到原分辨率 发现人物位置变了

**Comment by williamyang1991** [comment]
我们需要保证输入的长宽能被8整除，所以会crop和resize输入。你可以根据下面的参数重新放回crop的区域。

https://github.com/williamyang1991/StyleGANEX/blob/e593d16006f64b1e105c04eeb4a7cc149c1aca98/inversion.py#L79-L81

**Comment by zhanghongyong123456** [comment]
> 我们需要保证输入的长宽能被8整除，所以会crop和resize输入。你可以根据下面的参数重新放回crop的区域。
> 
> https://github.com/williamyang1991/StyleGANEX/blob/e593d16006f64b1e105c04eeb4a7cc149c1aca98/inversion.py#L79-L81

非常感谢，谢谢
