### ISSUE TITLE
about the padding calculation when use dilation

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [williamyang1991/StyleGANEX#16]
hi @williamyang1991 
why the padding is calculated as `self.padding = kernel_size // 2 + dilation - 1` instead of  `self.padding = (kernel_size - 1) // 2 * dilation`

**Comment by williamyang1991** [comment]
If dilation is 1, the former gives `kernel_size // 2`, while the latter gives `(kernel_size-1) // 2`.
The former is correct for an even number of kernel_size.

**Comment by zimenglan-sysu-512** [comment]
when dilation is odd and larger than 1, it seems not correct. e.g. kernel_size=5, dilation=5, former is 6, latter is 10

**Comment by williamyang1991** [comment]
but in this work, all dilation is a even number, e.g., 2, 4, 8, except 1

**Comment by williamyang1991** [comment]
I know the reason. 
Your equation should be correct. 
Since StyleGAN uses kernel_size=3, so `kernel_size // 2 + dilation - 1 = (kernel_size - 1) // 2 * dilation =  dilation`

**Comment by williamyang1991** [comment]
I have revised the code. Thank you!
