### ISSUE TITLE
Training code

### ISSUE THREAD

**Issue by baopmessi** [williamyang1991/StyleGANEX#2]
thanks for your awesome works! Can you please let us know when the training code will be released

**Comment by williamyang1991** [comment]
This paper is under review. Once it is accepted, we will release the training code.

Our code is mainly based on the code from https://github.com/eladrich/pixel2style2pixel
If you are interested, you can adapt the training code from pixel2style2pixel

**Comment by baopmessi** [comment]
Hi, any update for the training code. I look forward to the code.

**Comment by williamyang1991** [comment]
Hi, @baopmessi our paper is finally accepted by ICCV23, and we have released the training code!

**Comment by baopmessi** [comment]
> Hi, @baopmessi our paper is finally accepted by ICCV23, and we have released the training code!

Thanks you for updating the information!
