### ISSUE TITLE
Ajust Age

### ISSUE THREAD

**Issue by christopherohit** [williamyang1991/StyleGANEX#22]
Firstly thank you for the wonderful project.

But I am stuck when running it to Age editing, I can't find a param to change the age
Can you explain which i param will make an object in the image older than 
Thank you
<img width="880" alt="Screenshot 2023-12-25 at 14 33 38" src="https://github.com/williamyang1991/StyleGANEX/assets/55018999/9800d37e-4c62-432c-9658-33a145a63178">

**Comment by williamyang1991** [comment]
``` 
wplus_hat - 1 * editing_w # turn young
```

```
wplus_hat + 1 * editing_w # turn old
```

**Comment by christopherohit** [comment]
Yeah thanks you so much
