### ISSUE TITLE
Question about video editing training.

### ISSUE THREAD

**Issue by Dratlan** [williamyang1991/StyleGANEX#26]
Thanks for your great work! I'm now trying to train a new edit direction: slender. I'm a little confused about the data preparing. In data.config it shows the realign320 for training. but in the paper says training with generated data. besides, is it all the 70000 in-the-wild image are used for training and testing?

**Comment by williamyang1991** [comment]
```
We process FFHQ [17] to obtain 70,000 aligned training images of 1280 × 1280 resolution for all tasks except two video-related tasks that use StyleGAN generated data.
```

Only video editing and video stylization use generated data.

Other tasks use realign320 for training.

Yes, we use all 70000 images for training.

**Comment by Dratlan** [comment]
Got it, thanks for your quick relpy
