### ISSUE TITLE
Video toonify training

### ISSUE THREAD

**Issue by Dratlan** [williamyang1991/StyleGANEX#27]
Thanks for your great work. what's the data organization in video toonify(eg, what's in 'toonify_in': 'data/train/pixar/trainA/'), and other style like arcane, comic, cartoon, ukyio,etc. The toonify dataset in my download was not organized. thank you for your reply

**Comment by williamyang1991** [comment]
I just uses StyleGAN and Toonify to generate paired data from the same latent w
and put most of them into data/train/pixar/trainA/ and data/train/pixar/trainB/, 
and part of them data/train/pixar/testA/ and data/train/pixar/testB/

left three images are toonify_in, right three images are toonify_out
![image](https://github.com/user-attachments/assets/7758fb93-7215-4c96-bd18-a6a2a966807e)

**Comment by Dratlan** [comment]
> I just uses StyleGAN and Toonify to generate paired data from the same latent w and put most of them into data/train/pixar/trainA/ and data/train/pixar/trainB/, and part of them data/train/pixar/testA/ and data/train/pixar/testB/
> 
> left three images are toonify_in, right three images are toonify_out ![image](https://private-user-images.githubusercontent.com/18130694/348771871-7758fb93-7215-4c96-bd18-a6a2a966807e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDI3MDAsIm5iZiI6MTcyMTEwMjQwMCwicGF0aCI6Ii8xODEzMDY5NC8zNDg3NzE4NzEtNzc1OGZiOTMtNzIxNS00Yzk2LWJkMTgtYTZhMmE5NjY4MDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA0MDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjM2NhNjk0MjY5YjU3NjI2ZTNkOWRkMzE4YzNjMDA1MjcwYWVmZjJlZTYzMjg2ZjNmOTJkOWRiYWM0YzI2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2jUyy9pbIcX6XQN_v3tUBYunRXeQk-mcnFRYJwoaldw)



> I just uses StyleGAN and Toonify to generate paired data from the same latent w and put most of them into data/train/pixar/trainA/ and data/train/pixar/trainB/, and part of them data/train/pixar/testA/ and data/train/pixar/testB/
> 
> left three images are toonify_in, right three images are toonify_out ![image](https://private-user-images.githubusercontent.com/18130694/348771871-7758fb93-7215-4c96-bd18-a6a2a966807e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMDI3MDAsIm5iZiI6MTcyMTEwMjQwMCwicGF0aCI6Ii8xODEzMDY5NC8zNDg3NzE4NzEtNzc1OGZiOTMtNzIxNS00Yzk2LWJkMTgtYTZhMmE5NjY4MDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDA0MDAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjM2NhNjk0MjY5YjU3NjI2ZTNkOWRkMzE4YzNjMDA1MjcwYWVmZjJlZTYzMjg2ZjNmOTJkOWRiYWM0YzI2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2jUyy9pbIcX6XQN_v3tUBYunRXeQk-mcnFRYJwoaldw)

Thanks for your quick reply. I got one more question, for hair edit in this paper, it mainly changes the color, can i remove/change/enrich Hair from Portraits? or for a new attribute, how can i find its related edit_w

**Comment by williamyang1991** [comment]
You should refer to the related StyleGAN-based editing method like InterFaceGAN or LowRankGAN.

**Comment by Dratlan** [comment]
Thanks
