### ISSUE TITLE
Style_id in VToonify-D

### ISSUE THREAD

**Issue by Dratlan** [williamyang1991/StyleGANEX#29]
Hi, I've seen your previous work VToonify, I'am wondering if StyleGANEX supports free style in cartoon/pixar/arcane by using style_id in VToonify-D? Thanks

**Comment by williamyang1991** [comment]
We just test on extending StyleGAN model to StyleGANEX.
We haven't had time to work on extending DualStyleGAN model.
But I believe it should work.

**Comment by Dratlan** [comment]
Thanks, I'll have a try
