### ISSUE TITLE
Download failed - no file

### ISSUE THREAD

**Issue by tralala87** [williamyang1991/StyleGANEX#3]
Hi. I can't seem to download a video after it has been made on web ui. I get "Download failed - no file" either if I try to save it as html or mp4 file.

**Comment by williamyang1991** [comment]
I can download the file
you can find the link of the mp4 from the web source code
And download with that link 
![image](https://user-images.githubusercontent.com/18130694/225789462-af9d43e3-af91-4c12-be8b-e003eb896d43.png)
