### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by tralala87** [williamyang1991/StyleGANEX#4]
Getting Unexpected end of JSON input error in google colab when Number of frames to toonify set to 1000. Also, can't toonify more than 3 seconds of length of a video.

**Comment by williamyang1991** [comment]
With only `Unexpected end of JSON input error`, I cannot figure out what is wrong. Maybe it is because there is some limit in the gradio UI. 

You can use the PART II of google colab to generate long video. That part should be has no problem.

**Comment by williamyang1991** [comment]
https://neptune.ai/blog/google-colab-dealing-with-files

![image](https://user-images.githubusercontent.com/18130694/226777259-ab1a7b7f-7bef-4376-bb80-4bb40a0d9c8b.png)
