### ISSUE TITLE
SyntaxError: 'return' outside function`

### ISSUE THREAD

**Issue by tralala87** [williamyang1991/StyleGANEX#5]
When running:

`python video_editing.py --ckpt STYLEGANEX_MODEL_PATH --data_path FACE_INPUT_PATH`

I get:

` File "/content/StyleGANEX/video_editing.py", line 81
    return
    ^
SyntaxError: 'return' outside function`

**Comment by williamyang1991** [comment]
Thank you for finding this error.
I have fixed it. Please update the code.

**Comment by tralala87** [comment]
new error:

Loading pSp from checkpoint: /content/StyleGANEX/styleganex_toonify_pixar.pt
Traceback (most recent call last):
  File "/content/StyleGANEX/video_editing.py", line 65, in <module>
    import wget, bz2
ModuleNotFoundError: No module named 'wget'

**Comment by williamyang1991** [comment]
https://stackoverflow.com/questions/51069716/importerror-no-module-named-wget

Import Error can be easily solved by searching Google
