### ISSUE TITLE
Video face editing

### ISSUE THREAD

**Issue by opetliak** [williamyang1991/StyleGANEX#7]
Did you train video face editing (e.g black hair) on aligned data? 
According to the paper, it uses a synthetic dataset from Stylegan2 or did I miss something? 
`(we can simply generate x and y from random latent code w+ with StyleGAN G_0)`

**Comment by williamyang1991** [comment]
![image](https://user-images.githubusercontent.com/18130694/233411288-15f49cb8-d2de-4be0-93af-d434681070dd.png)
